#!/bin/sh

# $FreeBSD$
# KEYWORD: firstboot
# PROVIDE: firstboot_jail
# REQUIRE: FILESYSTEMS NETWORKING SERVERS DAEMON LOGIN dhclient
# BEFORE: LOGIN

## Modified from cperciva's sysutils/firstboot-pkgs

# Add the following lines to /etc/rc.conf.local or /etc/rc.conf (in the disk
# image, since this only runs on the first boot) to enable this:
#
# firstboot_jail_enable="YES"
#
# and optionally set the HTTP_PROXY IP:PORT part in firstboot_jail_squid, e.g.,
#
# firstboot_jail_squid="192.168.255.201:3128"
#
# and optionally set the deploy_XXX script in firstboot_jail_deploy, e.g.,
#
# firstboot_jail_deploy="squid"
#
# and optionally set the FQDN in firstboot_jail_fqdn, e.g.,
#
# firstboot_jail_fqdn="virtual.local"
#
# and optionally set the REPOSRC in firstboot_jail_reposrc, e.g.,
#
# firstboot_jail_reposrc="https://github.com/"

. /etc/rc.subr

: ${firstboot_jail_enable:="NO"}

name="firstboot_jail"
rcvar=firstboot_jail_enable
start_cmd="firstboot_jail_run"
stop_cmd=":"

firstboot_jail_run()
{

    ## Set HOME so we have the right HOME folder
    # echo "HOME var before: $HOME"
    HOME=/root
    export HOME
    ## set PATH so fres can find git
    PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:${HOME}/bin"
    export PATH
    # echo "HOME var after: $HOME"

    if [ "x" != "x${firstboot_jail_squid}" ]; then
        echo "RUN: env SQUID=${firstboot_jail_squid} setproxy"
                   env SQUID=${firstboot_jail_squid} setproxy
        ## export HTTP_PROXY for psnap
        HTTP_PROXY="http://${firstboot_jail_squid}"
        export HTTP_PROXY
    fi

    ## setup some vars that deploy scripts use
    if [ "x" != "x${firstboot_jail_fqdn}" ]; then
        FQDN=${firstboot_jail_fqdn}
        export FQDN
    fi
    if [ "x" != "x${firstboot_jail_reposrc}" ]; then
        REPOSRC=${firstboot_jail_reposrc}
        export REPOSRC
    fi

    ## Setup $HOME/bin , $HOME/git and more
    echo "RUN: fres"
               fres
    if [ -e ${HOME}/git/skel/bin/fres ]; then
        echo "RUN: rm -r ${HOME}/bin/"
                   rm -r ${HOME}/bin/
        sh ${HOME}/git/skel/bin/fres
    fi

    ## setup portsnap
    echo "RUN: psnap"
    psnap

    ## run deploy_${firstboot_jail_deploy}
    if which deploy_${firstboot_jail_deploy} >/dev/null 2>/dev/null ; then
        echo "RUN: deploy_${firstboot_jail_deploy}"
                   deploy_${firstboot_jail_deploy}
    fi

}

load_rc_config $name
run_rc_command "$1"
